substitutions:
  name: "sensor-pkg-b-ld2410"
  friendly_name: "Indoor Multi-Sensor Rev-B Pkg A Radar LD2410S"

  # Settings
  # voice name is one of: adam-dark-male, adam-male, eryn-informative-female, katie-x-female, lily-wolff-female, lucy-fresh-female, northern-terry-male,
  #    river-female
  voice_name: "adam-male"
  # Room name is one of: aj-room, bedroom, brisa-room, dining-room, entry-hallway, family-room, game-room, garage,guest-bathroom, guest-bedroom, hallway,
  #   kids-bathroom, kids-bedroom, kitchen, laundry-room, living-room, master-bathroom, master-bedroom, master-closet, master-toilet, noah-room, nursery,
  #   office, pantry, spare-bathroom, spare-bedroom, stairs, study, theater, utility-room, up-bathroom
  room_name: "bedroom"
  pir_installed: "true"
  # Status LED Configuration
  status_nightlight_brightness: "1.0"
  status_day_brightness: "0.5"
  status_night_brightness: "0.20"
  status_daytime_lux: "12.0"
  status_nighttime_lux: "7.0"
  presence_ha_entity: "binary_sensor.unknown_room_occupancy"
  # CO Configuration
  co_offset: "0.0"
  co_sensitivity: "2.000e-9"
  co_manufacture_date: "Not Set"
  co_serial_number: "Not Set"
  # Temperature Configuration
  temperature_offset: "0.0"
  # Humidity Configuration
  humidity_offset: "0.0"
  # CO₂ Configuration
  co2_calibration_date: "Not Set"
  # Automatically controlled Vent
  vent_ha_entity: "fan.vent_id"
  vent_use_humidity: "true"
  vent_use_co2: "true"
  vent_min_on_time: "15"
  vent_hum_on_trigger: "10.0"
  vent_hum_off_trigger: "2.5"
  vent_co2_on_trigger: "1100"
  vent_co2_off_trigger: "900"

  # git ref, leave at main unless you know what you are doing
  # if you change be sure to change ref below also
  ref: "main"

packages:
  remote:
    url: https://github.com/mikelawrence/esphome-indoor-multi-sensor-config
    refresh: 1min
    ref: main
    files:
      # Main Config Files
      - common/common.yaml
      - common/pkga-sen6x.yaml
      - common/radar-ld2410s.yaml

      # ADDITIONAL SENSORS
      # Carbon Dioxide (CO) - Figaro TGS5141 sensor
      - common/add-co.yaml
      # Energy Usage - INA2XX sensors to measure Voltage, Current, Power and Energy Usage
      - common/add-ina2xx.yaml
      # Light Level - TSL2591 sensor
      - common/add-tsl2591.yaml
      # Barometric Pressure - BMP581 sensor
      - common/add-bmp581.yaml
      # Microphone - Adds Sound Level meter
      - common/add-microphone.yaml

      # FEATURES
      # Automatic Vent - Use humidity and CO₂ to control a bathroom vent
      # - common/feat-auto-vent.yaml
      # Smoke Alarm - Use PM and CO₂ for smoke alarm functionality
      # Danger: !!!This is experimental and may not work as expected!!!
      #         !!!DO NOT USE AS A PRIMARY SMOKE ALARM!!!
      #         !!!Use at your own risk!!!
      # - common/feat-smoke-alarm.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: Mike Lawrence.Indoor Multi-Sensor Rev-B Sens-Pkg-A LD2410S

# API is a requirement of the dashboard import.
# Grab a key from https://esphome.io/components/api.html
api:
#   encryption:
#     key:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome
    # password: !secret ota_password

# WiFi is required
wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   use_address: xxx.xxx.xxx.xxx

# Allows user to provision WiFi credentials with Bluetooth using Improv standard
esp32_improv:
  authorizer: none

# Allow user to provision WiFi credentials with USB port using Improv standard
improv_serial:
