packages:
  # Include all of the core configuration
  core: !include sensor-pkg-a-c4001-esp32-s3.yaml

esphome:
  # This will allow for project identification, configuration and updates.
  project:
    name: Mike Lawrence.Indoor Multi-Sensor
    # This will be replaced by the github workflows with the `release` version
    version: dev
  # Automatically add the mac address to the name so you can use a single firmware for all devices
  name_add_mac_suffix: true

# Allow HTTP OTA updates
ota:
  - platform: http_request
    id: ota_http_request

# Managed Updates via HTTP request
update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-a-c4001.manifest.json

# HTTP Request component
http_request:

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://mikelawrence/esphome-indoor-multi-sensor-config/sensor-pkg-a-c4001-esp32-s3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE to allow the user to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:
