substitutions:
  name: "sensor-pkg-a-ld2450-mtmz"
  friendly_name: "Indoor Multi-Sensor Pkg A Radar LD2450 MTMZ"
  version_suffix: ""

  # Settings
  use_pir_in_presence: "true"
  # Status LED Configuration
  status_day_brightness: "0.5"
  status_night_brightness: "0.20"
  status_daytime_lux: "12.0"
  status_nighttime_lux: "7.0"
  # CO Configuration
  co_temp_id: "temperature"
  co_offset: "0.0"
  co_sensitivity: "2.000e-9"
  co_manufacture_date: "Not Set"
  co_serial_number: "Not Set"
  # Temperature Configuration
  temperature_offset: "0.0"
  # Humidity Configuration
  humidity_offset: "0.0"
  # CO₂ Configuration
  co2_calibration_date: "Not Set"
  # Automatically controlled Vent
  vent_ha_entity: fan.vent_id
  vent_use_humidity: "true"
  vent_use_co2: "true"
  vent_min_on_time: "15"
  vent_hum_on_trigger: "10.0"
  vent_hum_off_trigger: "2.5"
  vent_co2_on_trigger: "1100"
  vent_co2_off_trigger: "900"
  # Smoke Alarm Configuration
  alarm_use_co: 'true'
  alarm_use_co2: 'true'
  alarm_use_pm: 'true'

esphome:
  project:
    name: Mike Lawrence.Indoor Multi-Sensor Sens-Pkg-A

packages:
  # keep @main so that it can be replaced for CI workflows
  # Main Config Files
  common: github://mikelawrence/esphome-indoor-multi-sensor-config/common/common.yaml@main
  sen6x: github://mikelawrence/esphome-indoor-multi-sensor-config/common/pkga-sen6x.yaml@main
  radar: github://mikelawrence/esphome-indoor-multi-sensor-config/common/radar-ld2450ml-mtmz.yaml@main

  # ADDITIONAL SENSORS
  # Carbon Dioxide (CO) - Figaro TGS5141 sensor
  co: github://mikelawrence/esphome-indoor-multi-sensor-config/common/add-co.yaml@main
  # Energy Usage - INA2XX sensor to measure Voltage, Power and Energy Usage
  ina2xx: github://mikelawrence/esphome-indoor-multi-sensor-config/common/add-ina2xx.yaml@main
  # Light Level - TSL2591 sensor
  tsl2591: github://mikelawrence/esphome-indoor-multi-sensor-config/common/add-tsl2591.yaml@main
  # Barometric Pressure - BMP581 sensor
  bmp581: github://mikelawrence/esphome-indoor-multi-sensor-config/common/add-bmp581.yaml@main
  # Microphone - Adds Sound Level meter
  mic: github://mikelawrence/esphome-indoor-multi-sensor-config/common/add-microphone.yaml@main

  # FEATURES
  # SEN6X Pressure Compensation - Adds pressure compensation to SEN6X
  press-comp: github://mikelawrence/esphome-indoor-multi-sensor-config/common/feat-sen6x-press-comp.yaml@main
  # Automatic Vent - Use humidity and CO₂ to control a bathroom vent
  # auto-vent: github://mikelawrence/esphome-indoor-multi-sensor-config/common/feat-auto-vent.yaml@main
  # Smoke Alarm - Use PM and CO₂ for smoke alarm functionality
  # smoke-alarm: github://mikelawrence/esphome-indoor-multi-sensor-config/common/feat-smoke-alarm.yaml@main

# Add custom components
external_components:
  - source: github://mikelawrence/esphome-components
    components: [sen5x, ld2450]

# API is a requirement of the dashboard import.
# Grab a key from https://esphome.io/components/api.html
api:
#   encryption:
#     key:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome
    # password: !secret ota_password

# WiFi is required
wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   use_address: xxx.xxx.xxx.xxx

# Allows user to provision WiFi credentials with Bluetooth using Improv standard
esp32_improv:
  authorizer: none

# Allow user to provision WiFi credentials with USB port using Improv standard
improv_serial:
