substitutions:
  tag: main

packages:
  # Grab the current tag, this overwrites latest tag in the core configuration
  tag: !include common/tag.yaml
  # Grab all of the core configuration
  core: !include sensor-pkg-b-ld2450-stsz-esp32-s3.yaml

esphome:
  # This will allow for project identification, configuration and updates.
  project:
    name: Mike Lawrence.Indoor Multi-Sensor
    # This will be replaced by the github workflows with the `release` version
    version: dev
  # Automatically add the mac address to the name so you can use a single firmware for all devices
  name_add_mac_suffix: true

# Allow HTTP OTA updates
ota:
  - platform: http_request
    id: ota_http_request

# Managed Updates via HTTP request
update:
  - platform: http_request
    id: update_http_request
    name: Indoor Multi-Sensor Firmware
    source: https://https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-b-ld2450-stsz.manifest.json

# HTTP Request component
http_request:

# When adopted this configuration is used
dashboard_import:
  package_import_url: https://github.com/mikelawrence/esphome-indoor-multi-sensor-config/releases/latest/download/sensor-pkg-b-ld2450-stsz-esp32-s3.yaml
  import_full_config: true
