packages:
  core: !include sensor-pkg-b-c4001-esp32-s3.yaml

esphome:
  project:
    name: Mike Lawrence.Indoor Multi-Sensor Sens-Pkg-B
    version: dev
  name_add_mac_suffix: true

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Indoor Multi-Sensor Firmware
    source: https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-b-c4001.manifest.json

http_request: null

dashboard_import:
  package_import_url: github://mikelawrence/esphome-indoor-multi-sensor-config/sensor-pkg-b-c4001-esp32-s3.yaml@main
  import_full_config: true

wifi:

esp32_improv:
  authorizer: none

improv_serial:
