substitutions:
  # This will be replaced by the github workflows with the `release` version
  version: dev

packages:
  # Grab all of the core configuration
  core: !include sensor-pkg-a-ld2450-mtmz-esp32-s3.yaml

esphome:
  project:
    name: Mike Lawrence.Indoor Multi-Sensor
    version: dev
  name_add_mac_suffix: true
ota:
  - platform: http_request
    id: ota_http_request
update:
  - platform: http_request
    id: update_http_request
    name: Indoor Multi-Sensor Firmware
    source: https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-a-ld2450-mtmz.manifest.json
http_request: null
dashboard_import:
  package_import_url: github://mikelawrence/esphome-indoor-multi-sensor-config/sensor-pkg-a-ld2450-mtmz-esp32-s3.yaml@${tag}
  import_full_config: true
