substitutions:
  name: "sensor-rev-b-pkg-a"
  friendly_name: "Indoor Multi-Sensor Rev-B Sens-Pkg-A C4001"
  voice_name: "lily-wolff-female"
  room_name: "none"
  pir_installed: "true"

packages:
  - !include common/common.yaml
  - !include common/pkga-sen6x.yaml
  - !include common/radar-c4001.yaml
  - !include common/add-co.yaml
  - !include common/add-ina2xx.yaml
  - !include common/add-tsl2591.yaml
  - !include common/add-bmp581.yaml
  - !include common/add-microphone.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: Mike Lawrence.${friendly_name}
    # keep version: dev so that it will be replaced by github workflows with the `release` version
    version: dev
  name_add_mac_suffix: true

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Indoor Multi-Sensor Firmware
    source: https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-a-c4001.manifest.json

http_request:

dashboard_import:
  package_import_url: github://mikelawrence/esphome-indoor-multi-sensor-config/sensor-pkg-a-c4001-esp32-s3.yaml@main
  import_full_config: true

wifi:

esp32_improv:
  authorizer: none

improv_serial:
