substitutions:
  tag: 2025.08.0
packages:
  tag: '!include common/tag.yaml'
  core: '!include sensor-pkg-a-c4001-esp32-s3.yaml'
esphome:
  project:
    name: Mike Lawrence.Indoor Multi-Sensor
    version: dev
  name_add_mac_suffix: true
ota:
  - platform: http_request
    id: ota_http_request
update:
  - platform: http_request
    id: update_http_request
    name: Indoor Multi-Sensor Firmware
    source: https://mikelawrence.github.io/esphome-indoor-multi-sensor-config/firmware/sensor-pkg-a-c4001.manifest.json
http_request: null
dashboard_import:
  package_import_url: https://github.com/mikelawrence/esphome-indoor-multi-sensor-config/releases/latest/download/sensor-pkg-a-c4001-esp32-s3.yaml
  import_full_config: true
