# Adds I2S microphone with sound level meter
i2s_audio:
  - id: mic_i2s
    i2s_lrclk_pin: GPIO40
    i2s_bclk_pin: GPIO42

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_audio_id: mic_i2s
    i2s_din_pin: GPIO41
    adc_type: external
    sample_rate: 16000
    channel: left

sensor:
  - platform: sound_level
    id: sound_level_platform
    passive: false
    measurement_duration: 60s
    rms:
      id: sound_level_rms
      name: "Sound Level RMS"
      device_class: signal_strength
    peak:
      id: sound_level_peak
      name: "Sound Level Peak"
      device_class: signal_strength
