# Adds Energy monitoring using the INA228 and INA238 I2C digital power monitors

# logger:
#   logs:
#     ina2xx: INFO

time:
  - platform: homeassistant
    id: !extend homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: "id(usb_c_power_sensor).reset_energy_counters();"

sensor:
  - platform: ina2xx_i2c
    id: usb_c_power_sensor
    i2c_id: i2c1_bus
    model: INA228
    shunt_resistance: 0.150ohm
    max_current: 1A
    adc_range: 0
    temperature_coefficient: 75
    update_interval: 60s
    bus_voltage:
      name: "USB-C Voltage"
      accuracy_decimals: 2
    power:
      name: "USB-C Power"
      accuracy_decimals: 2
    current:
      name: "USB-C Current"
      accuracy_decimals: 3
    energy:
      name: "USB-C Energy"
      accuracy_decimals: 2
  - platform: ina2xx_i2c
    id: digital_power_sensor
    i2c_id: i2c1_bus
    model: INA238
    address: 0x42
    shunt_resistance: 0.068ohm
    max_current: 600mA
    adc_range: 0
    update_interval: 60s
    bus_voltage:
      name: "Digital Voltage"
      accuracy_decimals: 2
    power:
      name: "Digital Power"
      accuracy_decimals: 2
    current:
      name: "Digital Current"
      accuracy_decimals: 3
  - platform: ina2xx_i2c
    id: analog_power_sensor
    i2c_id: i2c1_bus
    model: INA238
    address: 0x43
    shunt_resistance: 0.080ohm
    max_current: 600mA
    adc_range: 0
    update_interval: 60s
    bus_voltage:
      name: "Analog Voltage"
      accuracy_decimals: 2
    power:
      name: "Analog Power"
      accuracy_decimals: 2
    current:
      name: "Analog Current"
      accuracy_decimals: 3
