# Adds Absolute Pressure using the BMP581 I2C digital pressure sensor
sensor:
  - platform: bmp581
    id: bmp581_sensor
    i2c_id: i2c1_bus
    address: 0x47
    update_interval: 2s
    pressure:
      name: "Pressure"
      id: pressure
      accuracy_decimals: 0
      oversampling: 128x
      filters:
        - throttle_average: 60s
      on_value:
        then:
          - lambda: |-
              if(id(co2_available_var))
              {
                if (id(sen6x_available_var))
                {
                  // compensate SEN6X CO₂ reading with current pressure
                  id(sen66_sensor)->set_ambient_pressure_compensation(x * 0.01); // convert to hPa
                }
                else
                {
                  // compensate SCD4X CO₂ reading with current pressure
                  id(scd41_sensor)->set_ambient_pressure_compensation(x * 0.01); // convert to hPa
                }
              }

