# PACKAGE A
#   Adds SHT4X temperature sensor as a board temperature sensor
#   Not compatible with PACKAGE B package
esphome:
  on_boot:
    priority: 600.0
    then:
      - lambda: |-
          id(sht4x_available) = true;

sensor:
  - platform: sht4x
    id: sht4x_sensor
    i2c_id: i2c1_bus
    update_interval: 1s
    temperature:
      id: sht4x_temperature
      accuracy_decimals: 2
      filters:
        - filter_out: NAN
        - lambda: |-
            // get the first board temperature out quickly
            if(isnan(id(board_temperature))) {
              id(board_temperature) = x;
            }
            return x;
        - throttle_average: 60s
      on_value:
        then:
          - lambda: |-
              id(board_temperature) = x;
