# PACKAGE A
#   Adds SEN66 sensors:
#     Temperature, Humidity, Carbon Dioxide (CO₂),
#     Volatile Organic Compounds (VOC), Nitrous Oxides (NOx) and
#     Particulate Matter (PM)
#   Not compatible with PACKAGE B packages
substitutions:
  # These are the default values for substitutions that are not defined in the main config file
  sen66_skip_initial: "300"
  temperature_offset: "0.0"
  humidity_offset: "0.0"
  co2_calibration_date: "Not Set"

external_components:
  - source: github://pr#9254
    components: [sen5x]
    refresh: 1min

esphome:
  on_boot:
    priority: 800.0
    then:
      - lambda: |-
          // Let other parts of config know there is a CO₂ sensor
          id(co2_available_var) = true;
          // Let other parts of config know there is a Particulate Matter sensor
          id(pm25_available_var) = true;

api:
  on_client_connected:
    then:
      - text_sensor.template.publish:
          id: co2_calibration_date
          state: ${co2_calibration_date}

interval:
  - interval: 7d
    startup_delay: 1d
    then:
      - sen5x.start_fan_autoclean: sen66_sensor

i2c:
  - id: i2c2_bus
    sda: GPIO43
    scl: GPIO44
    frequency: 400kHz
    scan: true

number:
  - platform: template
    id: co2_forced_cal_value
    name: "CO₂ Calibration Value"
    device_class: carbon_dioxide
    entity_category: config
    optimistic: true
    max_value: 1200
    min_value: 400
    step: 1
    initial_value: 420
    set_action:
      - delay: 1s

button:
  - platform: template
    name: "Start Fan Auto Clean"
    entity_category: config
    on_press:
      - sen5x.start_fan_autoclean: sen66_sensor
  - platform: template
    name: "Activate SHT Heater"
    entity_category: config
    on_press:
      - sen5x.activate_heater: sen66_sensor
  - platform: template
    name: "CO₂ Calibrate"
    entity_category: config
    on_press:
      - sen5x.perform_forced_co2_calibration:
          value: !lambda |-
            float value = id(co2_forced_cal_value).state;
            ESP_LOGD("scd4x", "CO₂ Calibration executed, CO₂=%0.0f", value);
            return value;
          id: sen66_sensor

sensor:
  - platform: sen5x
    id: sen66_sensor
    i2c_id: i2c2_bus
    address: 0x6B
    update_interval: 1s
    model: SEN66
    store_baseline: true
    temperature:
      # temperature 1s interval averaged to once a minute
      # first 5 minutes ignored
      id: temperature_internal
      accuracy_decimals: 2
      filters:
        - filter_out: NAN
        - skip_initial: ${sen66_skip_initial}
        - throttle_average: 60s
    humidity:
      # humidity 1s interval averaged to once a minute
      # first 5 minutes ignored
      id: humidity_internal
      accuracy_decimals: 2
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - offset: ${humidity_offset}
        - throttle_average: 60s
    pm_1_0:
      # PM 1µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <1um Mass concentration"
      id: pm_1_0
      accuracy_decimals: 2
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
    pm_2_5:
      # PM 2.5µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <2.5um Mass concentration"
      id: pm_2_5
      accuracy_decimals: 2
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
    pm_4_0:
      # PM 4µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <4um Mass concentration"
      id: pm_4_0
      accuracy_decimals: 2
      filters: 
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
    pm_10_0:
      # PM 10µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <10um Mass concentration"
      id: pm_10_0
      accuracy_decimals: 2
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
    co2:
      # CO₂ internal 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "CO₂"
      id: co2
      automatic_self_calibration: false
      accuracy_decimals: 0
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
      on_value:
        then:
          - lambda: |-
              if (id(pressure_hpa_var) > 0.0)
                id(sen66_sensor).set_ambient_pressure_compensation(id(pressure_hpa_var));
              if (x > 2000.0)
                id(co2_warning_var) = true;
              if (x < 1800.0)
                id(co2_warning_var) = false;
    nox:
      # NOₓ 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "NOₓ"
      id: nox
      accuracy_decimals: 0
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
    voc:
      # VOC 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "VOC"
      id: voc
      accuracy_decimals: 0
      filters:
        - skip_initial: ${sen66_skip_initial}
        - filter_out: NAN
        - throttle_average: 60s
  - platform: copy
    # temperature_internal median over last 5 minutes, output every minute
    id: temperature
    name: "Temperature"
    accuracy_decimals: 2
    source_id: temperature_internal
    filters:
      - offset: ${temperature_offset}
      - median:
          window_size: 5
          send_every: 1
  - platform: copy
    # humidity_internal median over last 5 minutes, output every minute
    id: humidity
    name: "Humidity"
    source_id: humidity_internal
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 5
          send_every: 1
  - platform: copy
    id: pm_2_5_5min_avg
    source_id: pm_2_5
    filters:
      - exponential_moving_average:
          # 1 / (samples + 1) = 1 / 6
          alpha: 0.16666667
          send_every: 1
    on_value:
      then:
        - lambda: |-
            if (x > 1000.0)
              id(pm25_warning_var) = true;
            else if (x < 900.0)
              id(pm25_warning_var) = false;
            if (x > 1500.0)
              id(pm25_alarm_var) = true;
            else if (x < 1350.0)
              id(pm25_alarm_var) = false;
  - platform: copy
    id: pm_2_5_60min_avg
    source_id: pm_2_5
    filters:
      - exponential_moving_average:
          # 1 / (samples + 1) = 1 / 61
          alpha: 0.01639344
          send_every: 1
    on_value:
      then:
        - lambda: |-
            if (x > 55.0)
              id(pm25_warning_var) = true;
            else if (x < 49.5)
              id(pm25_warning_var) = false;
            if (x > 150.0)
              id(pm25_alarm_var) = true;
            else if (x < 135.0)
              id(pm25_alarm_var) = false;
text_sensor:
  - platform: template
    name: "CO₂ Calibration Date"
    id: co2_calibration_date
    entity_category: diagnostic
    update_interval: never
    lambda: 'return {""};'
