# PACKAGE A
#   Adds SEN66 sensors:
#     Temperature, Humidity, Carbon Dioxide (CO₂),
#     Volatile Organic Compounds (VOC), Nitrous Oxides (NOx) and
#     Particulate Matter (PM)
#   Not compatible with PACKAGE B packages
esphome:
  on_boot:
    priority: 600.0
    then:
      - lambda: |-
          id(co2_available) = true;
          id(pm25_available) = true;

api:
  on_client_connected:
    then:
      - text_sensor.template.publish:
          id: co2_calibration_date
          state: ${co2_calibration_date}

i2c:
  - id: i2c2_bus
    sda: GPIO43
    scl: GPIO44
    frequency: 400kHz
    scan: true

number:
  - platform: template
    id: co2_forced_cal_value
    name: "CO₂ Calibration Value"
    device_class: carbon_dioxide
    entity_category: CONFIG
    optimistic: true
    max_value: 1200
    min_value: 400
    step: 1
    initial_value: 420
    set_action:
      - delay: 1s

button:
  - platform: template
    name: "Start Fan Auto Clean"
    entity_category: CONFIG
    on_press:
      - sen5x.start_fan_autoclean: sen66_sensor
  - platform: template
    name: "Activate SHT Heater"
    entity_category: CONFIG
    on_press:
      - sen5x.activate_heater: sen66_sensor
  - platform: template
    name: "CO₂ Calibrate"
    entity_category: CONFIG
    on_press:
      - sen5x.perform_forced_co2_calibration:
          value: !lambda |-
            float value = id(co2_forced_cal_value).state;
            ESP_LOGD("scd4x", "CO₂ Calibration executed, CO₂=%0.0f", value);
            return value;
          id: sen66_sensor

sensor:
  - platform: sen5x
    id: sen66_sensor
    i2c_id: i2c2_bus
    address: 0x6B
    update_interval: 1s
    setup_priority: -400
    model: SEN66
    store_baseline: true
    temperature:
      # temperature 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "Temperature"
      id: temperature
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - offset: ${temperature_offset}
        - throttle_average: 60s
    humidity:
      # humidity 1s interval averaged to once a minute
      # first 5 minutes ignored
      id: humidity
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - offset: ${humidity_offset}
    pm_1_0:
      # PM 1µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
    pm_2_5:
      # PM 2.5µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      id: pm_2_5
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
    pm_4_0:
      # PM 4µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
    pm_10_0:
      # PM 10µm 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 2
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
    co2:
      # CO₂ internal 1s interval averaged to once a minute
      # first 5 minutes ignored
      id: co2
      automatic_self_calibration: false
      accuracy_decimals: 0
      filters:
        - skip_initial: 300
        - filter_out: NAN
    nox:
      # NOx 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "NOx"
      id: nox
      accuracy_decimals: 0
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
    voc:
      # VOC 1s interval averaged to once a minute
      # first 5 minutes ignored
      name: "VOC"
      id: voc
      accuracy_decimals: 0
      filters:
        - skip_initial: 300
        - filter_out: NAN
        - throttle_average: 60s
  - platform: copy
    id: humidity_internal
    source_id: humidity
  - platform: copy
    id: pm_2_5_internal
    source_id: pm_2_5
    on_value:
      then:
        - lambda: |-
            if (x > 35.0) {
              id(pm25_warning) = true;
            }
            if (x < 31.5) {
              id(pm25_warning) = false;
            }
            if (x > 75.0) {
              id(pm25_alarm) = true;
            }
            if (x < 67.5) {
              id(pm25_alarm) = false;
            }
  - platform: copy
    id: co2_internal
    source_id: co2
text_sensor:
  - platform: template
    name: "CO₂ Calibration Date"
    id: co2_calibration_date
    entity_category: diagnostic
    update_interval: never
    lambda: 'return {""};'
