# PACKAGE B
#   Adds SHT45 sensors:
#     Temperature and Humidity
#   Not compatible with PACKAGE A package
number:
  - platform: template
    name: "Temperature Calibration Offset"
    id: temperature_calibration_offset
    device_class: temperature
    entity_category: config
    optimistic: true
    max_value: 10.0
    min_value: -10.0
    step: 0.1
    initial_value: 0.0
    restore_value: true
  - platform: template
    name: "Humidity Calibration Offset"
    id: humidity_calibration_offset
    device_class: humidity
    entity_category: config
    optimistic: true
    max_value: 20.0
    min_value: -20.0
    step: 0.1
    initial_value: 0.0
    restore_value: true

sensor:
  - platform: sht4x
    id: sht4x_sensor
    i2c_id: i2c1_bus
    update_interval: 1s
    temperature:
      # temperature_internal has 1s interval averaged to once a minute
      id: temperature_internal
      accuracy_decimals: 2
      filters:
        - filter_out: NAN
        - offset: !lambda return id(temperature_calibration_offset).state;
        - throttle_average: 60s
    humidity:
      # humidity_internal has 1s interval averaged to once a minute
      id: humidity_internal
      accuracy_decimals: 2
      filters:
        - filter_out: NAN
        - offset: !lambda return id(humidity_calibration_offset).state;
        - throttle_average: 60s
  - platform: copy
    # temperature median over last 5 minutes, output every minute
    id: temperature
    name: "Temperature"
    source_id: temperature_internal
    accuracy_decimals: 2
    filters:
      - offset: ${temperature_offset}
      - median:
          window_size: 5
          send_every: 1
  - platform: copy
    # humidity median over last 5 minutes, output every minute
    id: humidity
    name: "Humidity"
    source_id: humidity_internal
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 5
          send_every: 1
