# PACKAGE B
#   Adds SHT45 sensors:
#     Temperature and Humidity
#   Not compatible with PACKAGE A package
sensor:
  - platform: sht4x
    id: sht4x_sensor
    i2c_id: i2c1_bus
    update_interval: 1s
    temperature:
      # temperature 1s interval averaged to once a minute
      # then median over last 5 minutes, output every minute
      id: temperature
      name: "Temperature"
      accuracy_decimals: 2
      filters:
        - offset: ${temperature_offset}
        - filter_out: NAN
        - lambda: |-
            // get the first board temperature out quickly
            if(isnan(id(board_temperature))) {
              id(board_temperature) = x;
            }
            return x;
        - throttle_average: 60s
        # - median:
        #     window_size: 5
        #     send_every: 1
      on_value:
        then:
          - lambda: |-
              id(board_temperature) = x;
    humidity:
      # humidity 1s interval averaged to once a minute
      id: humidity_internal
      accuracy_decimals: 2
      filters:
        - offset: ${humidity_offset}
        - filter_out: NAN
        - throttle_average: 60s
  - platform: copy
    # median humidity_internal over last 5 minutes, output every minute
    id: humidity
    name: "Humidity"
    source_id: humidity_internal
    # filters:
    #   - median:
    #       window_size: 5
    #       send_every: 1
