# PACKAGE B
#   Adds SHT45 sensors:
#     Temperature and Humidity
#   Not compatible with PACKAGE A package
substitutions:
  temperature_offset: "0.0"
  humidity_offset: "0.0"

esphome:
  on_boot:
    priority: 600.0
    then:
      - lambda: |-
          id(sht4x_available_var) = true;

sensor:
  - platform: sht4x
    id: sht4x_sensor
    i2c_id: i2c1_bus
    update_interval: 1s
    temperature:
      # temperature_internal has 1s interval averaged to once a minute
      id: temperature_internal
      accuracy_decimals: 2
      filters:
        - filter_out: NAN
        - lambda: |-
            // get the first board temperature out quickly
            if(isnan(id(board_temperature_var)))
              id(board_temperature_var) = x;
            return x;
        - throttle_average: 60s
      on_value:
        then:
          - lambda: |-
              id(board_temperature_var) = x;
    humidity:
      # humidity_internal has 1s interval averaged to once a minute
      id: humidity_internal
      accuracy_decimals: 2
      filters:
        - offset: ${humidity_offset}
        - filter_out: NAN
        - throttle_average: 60s
  - platform: copy
    # temperature median over last 5 minutes, output every minute
    id: temperature
    name: "Temperature"
    source_id: temperature_internal
    accuracy_decimals: 2
    filters:
      - offset: ${temperature_offset}
      - median:
          window_size: 5
          send_every: 1
  - platform: copy
    id: sht4x_temperature
    accuracy_decimals: 2
    source_id: temperature_internal
  - platform: copy
    # humidity median over last 5 minutes, output every minute
    id: humidity
    name: "Humidity"
    source_id: humidity_internal
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 5
          send_every: 1
