# PACKAGE B
#   Adds SCD41 sensors:
#     Carbon Dioxide (CO₂)
#   Not compatible with PACKAGE A package
esphome:
  on_boot:
    priority: 600.0
    then:
      - lambda: |-
          id(co2_available_var) = true;

api:
  on_client_connected:
    then:
      - text_sensor.template.publish:
          id: co2_calibration_date
          state: ${co2_calibration_date}

sensor:
  - platform: scd4x
    id: scd41_sensor
    i2c_id: i2c1_bus
    update_interval: 10s
    automatic_self_calibration: false
    co2:
      name: "CO₂"
      id: co2
      accuracy_decimals: 0
      filters:
        - filter_out: NAN
        - throttle_average: 60s
  - platform: copy
    id: co2_internal
    source_id: co2
    on_value:
      then:
        - lambda: |-
            if (x > 2000.0)
              id(co2_warning_var) = true;
            if (x < 1800.0)
              id(co2_warning_var) = false;

number:
  - platform: template
    id: co2_forced_cal_value
    name: "CO₂ Calibration Value"
    device_class: carbon_dioxide
    entity_category: configuration
    optimistic: true
    max_value: 1200
    min_value: 400
    step: 1
    initial_value: 420
    set_action:
      - delay: 1s

button:
  - platform: template
    name: "CO₂ Calibrate"
    id: co2_calibrate
    entity_category: configuration
    on_press:
      - scd4x.perform_forced_calibration:
          value: !lambda |-
            float value = id(co2_forced_cal_value).state;
            ESP_LOGD("scd4x", "CO₂ Calibration executed, CO₂=%0.0f", value);
            return value;
          id: scd41_sensor

text_sensor:
  - platform: template
    name: "CO₂ Calibration Date"
    id: co2_calibration_date
    entity_category: diagnostic
    update_interval: never
    lambda: 'return {""};'
