# PACKAGE B
#   Adds SCD41 sensors:
#     Carbon Dioxide (CO₂)
#   Not compatible with PACKAGE A package
esphome:
  on_boot:
    priority: 800.0
    then:
      - lambda: |-
          // Let other parts of config know there is a CO₂ sensor
          id(co2_available_var) = true;

button:
  - platform: template
    name: "CO₂ Force Calibrate"
    entity_category: config
    on_press:
      - scd4x.perform_forced_calibration:
          value: !lambda |-
            float value = id(co2_forced_calibration_offset).state;
            ESP_LOGD("scd4x", "CO₂ Force Calibration executed, CO₂=%0.0f", value);
            return value;
          id: scd41_sensor

datetime:
  - platform: template
    id: co2_calibration_date
    type: date
    name: "CO₂ Calibration Date"
    optimistic: yes
    initial_value: "1970-01-01"
    restore_value: true

number:
  - platform: template
    id: co2_forced_calibration_offset
    name: "CO₂ Forced Calibration Offset"
    device_class: carbon_dioxide
    entity_category: config
    optimistic: true
    max_value: 1200
    min_value: 400
    step: 1
    initial_value: 420

sensor:
  - platform: scd4x
    id: scd41_sensor
    i2c_id: i2c1_bus
    update_interval: 10s
    automatic_self_calibration: false
    co2:
      name: "CO₂"
      id: co2
      accuracy_decimals: 0
      filters:
        - filter_out: NAN
        - throttle_average: 60s
      on_value:
        then:
          - lambda: |-
              if (id(pressure_hpa_var) > 0.0)
                id(scd41_sensor).set_ambient_pressure_compensation(id(pressure_hpa_var));
              if (x > 2000.0)
                id(co2_warning_var) = true;
              if (x < 1800.0)
                id(co2_warning_var) = false;
