# Adds DFRobot C4001 (SEN0609 or SEN0610) mmWave Radar
# Current this is my PR on ESPHome, there is a new PR from the DFRobot in progress
#   Expect changes to that component when ready
# Not compatible with any other radar package
external_components:
  - source: github://pr#9810
    components: [dfrobot_c4001]
    refresh: 1min

api:
  on_client_connected:
    then:
      - text_sensor.template.publish:
          id: radar_included
          state: "Hi-Link LD2410"

power_supply:
  # enables power to the C4001 module
  - id: "c4001_enable"
    pin: GPIO15
    enable_on_boot: true

uart:
  - id: c4001_uart
    tx_pin: GPIO18
    rx_pin: GPIO17
    baud_rate: 9600

dfrobot_c4001:
  id: c4001_radar
  uart_id: c4001_uart
  model: SEN0609
  mode: PRESENCE

button:
  - platform: dfrobot_c4001
    config_save:
      name: C4001 Config Save
    factory_reset:
      name: C4001 Factory Reset
    restart:
      name: C4001 Restart

number:
  - platform: dfrobot_c4001
    dfrobot_c4001_id: c4001_radar
    max_range:
      name: Range Max
      id: max_range
    min_range:
      name: Range Min
      id: min_range
    trigger_range:
      name: Range Trigger
      id:
    hold_sensitivity:
      name: Sensitivity Hold
      id: trigger_range
    trigger_sensitivity:
      name: Sensitivity Trigger
      id: trigger_sensitivity
    on_latency:
      name: Latency On
      id: on_latency
    off_latency:
      name: Latency Off
      id: off_latency
    inhibit_time:
      name: Inhibit Time
      id: inhibit_time

binary_sensor:
  - platform: dfrobot_c4001
    occupancy:
      name: MMWAVE Presence
      id: presence_mmwave
    config_changed:
      name: C4001 Config Changed

switch:
  - platform: dfrobot_c4001
    dfrobot_c4001_id: c4001_radar
    out_led_enable:
      name: C4001 Enable OUT LED
    run_led_enable:
      name: C4001 Enable RUN LED

text_sensor:
  - platform: dfrobot_c4001
    dfrobot_c4001_id: c4001_radar
    software_version:
      name: C4001 Software Version
    hardware_version:
      name: C4001 Hardware Version
  - platform: template
    name: "Radar Included"
    id: radar_included
    entity_category: diagnostic
    update_interval: never
    lambda: 'return {""};'
