# Adds No Radar
# Not compatible with any other radar package
substitutions:
  # SEN6X Temperature Compensation values when there is no radar
  sen66_to_offset: "-1.462"
  sen66_to_slope: "-0.044"
  sen66_to_time_constant: "1186"
