# Adds Hi-Link LD2410S mmWave Radar
#   Not compatible with any other radar package
substitutions:
  # SEN6X Temperature Compensation values as specific to the LD2410S radar module
  sen66_to_offset: "-1.152"
  sen66_to_slope: "-0.033"
  sen66_to_time_constant: "1233"
  # by default this is the tag to retrieve from github for the ld2410s component, can be overridden
  ld2410s_tag: "611a2334b3b0e77034daefb9eb3b20019626f163"  # 2026.08.0

external_components:
  - source: github://mikelawrence/esphome-component-ld2410s@${ld2410s_tag}

uart:
  - id: ld2410s_uart
    tx_pin: GPIO17
    rx_pin: GPIO18
    baud_rate: 115200
    parity: NONE
    stop_bits: 1

ld2410s:
  id: ld2410s_radar
  uart_id: ld2410s_uart

binary_sensor:
  - platform: template
    # executed every loop() call, about 16 ms
    name: "Presence"
    id: presence
    device_class: presence
    lambda: |-
      id(presence_var) = id(presence_mmwave).state || id(motion_pir).state;
      return id(presence_var);
    on_state:
      then:
        - script.execute: update_status_led
  - platform: ld2410s
    has_target:
      name: MMWAVE Presence
      id: presence_mmwave
      filters:
        - delayed_off: !lambda return static_cast<uint32_t>(id(timeout).state * 1000);
    cal_running:
      name: LD2410S Cal Running
      entity_category: diagnostic

button:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    cal_start:
      name: LD2410S Cal Start
      entity_category: config

number:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    max_detect_gate:
      name: Max Detect Gate
    min_detect_gate:
      name: Min Detect Gate
    no_delay:
      name: No Detect Report Delay
    status_reporting_frequency:
      id: status_reporting_frequency
      on_value_range:
        above: 4.1
        below: 3.9
        then:
          - number.set:
              id: status_reporting_frequency
              value: 4.0
          - logger.log:
              format: "Auto Set Status Reporting Frequency to 4.0Hz"
              tag: "radar-ld2410s"
    distance_reporting_frequency:
      id: distance_reporting_frequency
      on_value_range:
        above: 4.1
        below: 3.9
        then:
          - number.set:
              id: distance_reporting_frequency
              value: 4.0
          - logger.log:
              format: "Auto Set Distance Reporting Frequency to 4.0Hz"
              tag: "radar-ld2410s"
    g0:
      trigger_threshold:
        name: G0 Trigger Threshold
      hold_threshold:
        name: G0 Hold Threshold
    g1:
      trigger_threshold:
        name: G1 Trigger Threshold
      hold_threshold:
        name: G1 Hold Threshold
    g2:
      trigger_threshold:
        name: G2 Trigger Threshold
      hold_threshold:
        name: G2 Hold Threshold
    g3:
      trigger_threshold:
        name: G3 Trigger Threshold
      hold_threshold:
        name: G3 Hold Threshold
    g4:
      trigger_threshold:
        name: G4 Trigger Threshold
      hold_threshold:
        name: G4 Hold Threshold
    g5:
      trigger_threshold:
        name: G5 Trigger Threshold
      hold_threshold:
        name: G5 Hold Threshold
    g6:
      trigger_threshold:
        name: G6 Trigger Threshold
      hold_threshold:
        name: G6 Hold Threshold
    g7:
      trigger_threshold:
        name: G7 Trigger Threshold
      hold_threshold:
        name: G7 Hold Threshold
    g8:
      trigger_threshold:
        name: G8 Trigger Threshold
      hold_threshold:
        name: G8 Hold Threshold
    g9:
      trigger_threshold:
        name: G9 Trigger Threshold
      hold_threshold:
        name: G9 Hold Threshold
    g10:
      trigger_threshold:
        name: G10 Trigger Threshold
      hold_threshold:
        name: G10 Hold Threshold
    g11:
      trigger_threshold:
        name: G11 Trigger Threshold
      hold_threshold:
        name: G11 Hold Threshold
    g12:
      trigger_threshold:
        name: G12 Trigger Threshold
      hold_threshold:
        name: G12 Hold Threshold
    g13:
      trigger_threshold:
        name: G13 Trigger Threshold
      hold_threshold:
        name: G13 Hold Threshold
    g14:
      trigger_threshold:
        name: G14 Trigger Threshold
      hold_threshold:
        name: G14 Hold Threshold
    g15:
      trigger_threshold:
        name: G15 Trigger Threshold
      hold_threshold:
        name: G15 Hold Threshold

sensor:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    target_distance:
      name: Target Distance
    cal_progress:
      name: LD2410S Cal Progress
    g0_energy:
      name: G0 Energy
    g1_energy:
      name: G1 Energy
    g2_energy:
      name: G2 Energy
    g3_energy:
      name: G3 Energy
    g4_energy:
      name: G4 Energy
    g5_energy:
      name: G5 Energy
    g6_energy:
      name: G6 Energy
    g7_energy:
      name: G7 Energy
    g8_energy:
      name: G8 Energy
    g9_energy:
      name: G9 Energy
    g10_energy:
      name: G10 Energy
    g11_energy:
      name: G11 Energy
    g12_energy:
      name: G12 Energy
    g13_energy:
      name: G13 Energy
    g14_energy:
      name: G14 Energy
    g15_energy:
      name: G15 Energy

select:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    response_speed:
      name: Response Speed

switch:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    minimal_output:
      name: Minimal Output

text_sensor:
  - platform: ld2410s
    ld2410s_id: ld2410s_radar
    fw_version:
      name: LD2410S Firmware version
  - platform: template
    name: "Radar Included"
    id: radar_included
    entity_category: diagnostic
    update_interval: 600s
    lambda: !lambda return {"Hi-Link LD2410S"};
