# Adds DFRobot C4001 (SEN0609 or SEN0610) mmWave Radar
# Currently this is my PR on ESPHome, there is a new PR from the DFRobot in progress
# Not compatible with any other radar package
substitutions:
  # SEN6X Temperature Compensation values when there is no radar
  sen66_tc_offset: "0"
  sen66_tc_normalized_offset_slope: "0"
  sen66_tc_time_constant: "0"
