name: Create Pre-Release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get calendar version
        id: calendar-version
        uses: harm-matthias-harms/calendar-version@v3.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          sed -i 's/version:.*$/version: ${{ steps.calendar-version.outputs.new-version }}/g' ./common/common.yaml
          echo "{ \"version\": \"${{ steps.calendar-version.outputs.new-version }}\" }" > version.json

      - name: Commit version changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update Version automated commit"

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.calendar-version.outputs.new-version }}
          generate_release_notes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
