name: Create Pre-release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # ref: ${{ github.head_ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: Get calendar version
        id: calendar-version
        uses: harm-matthias-harms/calendar-version@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: common/version.yaml
          propertyPath: substitutions.common_version
          value: ${{ steps.calendar-version.outputs.new-version }}
          commitChange: true
          message: "Update version"
          branch: main

      - name: Push release tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          ref: main/${{ steps.calendar-version.outputs.new-version }}
          tag: ${{ steps.calendar-version.outputs.new-version }}
          message: ${{ steps.calendar-version.outputs.new-version }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.calendar-version.outputs.new-version }}
          generate_release_notes: true
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
