name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@025a1e6255610c498ed590403b7e510b69e474df  # 2026.4.1
    with:
      files: |
        rev-b-pkg-a-none-esp32-s3.factory.yaml
        rev-b-pkg-a-c4001-esp32-s3.factory.yaml
        rev-b-pkg-a-ld2410-esp32-s3.factory.yaml
        rev-b-pkg-a-ld2410s-esp32-s3.factory.yaml
        rev-b-pkg-a-ld2450-esp32-s3.factory.yaml
        rev-b-pkg-b-none-esp32-s3.factory.yaml
        rev-b-pkg-b-c4001-esp32-s3.factory.yaml
        rev-b-pkg-b-ld2410-esp32-s3.factory.yaml
        rev-b-pkg-b-ld2410s-esp32-s3.factory.yaml
        rev-b-pkg-b-ld2450-esp32-s3.factory.yaml
      esphome-version: latest
      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@025a1e6255610c498ed590403b7e510b69e474df  # 2026.4.1
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}
